# Generated by Django 2.2.5 on 2020-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200317_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartelement',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
